config/
db/
dist/
features/
**/node_modules/
script/
**/spec/
**/test/
**/tests/
Tests/
**/vendor/
**/*_test.go
**/*.d.ts
.github/
.idea/
requirements.txt
LICENSE
.gitignore
.codeclimate.json
.gitattributes
.dockerfile
CODE_OF_CONDUCT.md
CONTRIBUTING.md
CREDITS.md
ReadMe.md
SECURITY.md
extra/DataBase/
*.csv
*.json
